#!/usr/bin/with-contenv bash

. /etc/init-base
[[ ! -d ${CONFIG_DIR} ]] && mkdir /config
[[ -z $(ls -A ${CONFIG_DIR}/aria2/) ]] && cp -R /config.example/aria2 /config
[[ -z $(ls -A ${CONFIG_DIR}/nginx/) ]] && cp -R /config.example/nginx /config
[[ -z $(ls -A ${CONFIG_DIR}/samba/) ]] && cp -R /config.example/samba /config

chmod +x /usr/bin/addsmbuser
mkdir -p /config/alist
mkdir -p /var/log/samba/
mkdir -p "${DOWNLOAD_DIR}"
chown -R p3terx:p3terx /config/alist
PROFILES="
aria2.conf
script.conf
core
delete.sh
dht.dat
dht6.dat
LICENSE
"

DOWNLOAD_PROFILE


[[ ! -f "${ARIA2_CONF_DIR}/aria2.session" ]] && {
    rm -rf "${ARIA2_CONF_DIR}/aria2.session"
    touch "${ARIA2_CONF_DIR}/aria2.session"
}

if ! [[ "${UPDATE_TRACKERS}" = "false" || "${UPDATE_TRACKERS}" = "disable" ]]; then
    rm -f /etc/services.d/crond/down
    PROFILES="tracker.sh"
    DOWNLOAD_PROFILE
    bash ${SCRIPT_DIR}/tracker.sh ${ARIA2_CONF}
else
    touch /etc/services.d/crond/down
fi

CREATE_SAMBA_USER

exit 0
